### ISSUE TITLE
Missing repository cryptix/encodedTime

### ISSUE THREAD

**Issue by DrnSln** [cryptix/gohn#2]
When :

``` go
go run main.go
/mnt/src/go/src/github.com/cryptix/gohn/item.go:5:2: cannot find package "github.com/cryptix/encodedTime" in any of:
     /usr/local/go/src/github.com/cryptix/encodedTime (from $GOROOT)
```

and https://github.com/cryptix/encodedTime returns the _not found_ ( Err 404 )

**Comment by cryptix** [comment]
I forgot to update this import when I consolidated a couple of my packages into [one repo](https://github.com/cryptix/go). `git pull` or `go get -u` and it should work now. Sorry about that!
